name: Auto Merge Learned Words

on:
  push:
    paths:
      - 'learned/**.json'

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    steps:
      - name: Auto approve and merge
        uses: pascalgn/automerge-action@v0.15.5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
