name: Auto Save & Merge Learned Word

on:
  issues:
    types: [opened]

jobs:
  save-word:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v3

      - name: Setup Git
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'

      - name: Extract word & language
        id: extract
        run: |
          LANG=$(echo "${{ github.event.issue.title }}" | cut -d':' -f2)
          WORD=$(echo "${{ github.event.issue.body }}" | sed -n "s/Add \\\"\\(.*\\)\\\" to.*/\\1/p")
          BRANCH="learned-${LANG}-${RANDOM}"
          echo "lang=${LANG}" >> $GITHUB_OUTPUT
          echo "word=${WORD}" >> $GITHUB_OUTPUT
          echo "branch=${BRANCH}" >> $GITHUB_OUTPUT

      - name: Create and switch to new branch
        run: |
          git checkout -b ${{ steps.extract.outputs.branch }}

      - name: Update learned words JSON
        run: |
          FILE="data/learned_${{ steps.extract.outputs.lang }}.json"
          mkdir -p data
          if [ ! -f "$FILE" ]; then echo '{"words":[]}' > "$FILE"; fi
          jq --arg word "${{ steps.extract.outputs.word }}" '.words |= if index($word) == null then . + [$word] else . end' "$FILE" > tmp && mv tmp "$FILE"
          git add "$FILE"
          git commit -m "Add learned word: ${{ steps.extract.outputs.word }} (${{
            steps.extract.outputs.lang }})"
          git push origin ${{ steps.extract.outputs.branch }}

      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "Add learned word: ${{ steps.extract.outputs.word }}"
          branch: ${{ steps.extract.outputs.branch }}
          title: "Learned: ${{ steps.extract.outputs.word }}"
          body: "Automatically adding learned word."
          base: main

      - name: Auto-merge PR
        uses: pascalgn/automerge-action@v0.15.5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
