name: Auto Save & Merge Learned Word Pair

on:
  issues:
    types: [opened]

jobs:
  save-word-pair:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write # Still needed for gh pr create

    steps:
      - name: Checkout repository code
        uses: actions/checkout@v4

      - name: Setup Git User
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Extract word pair & language from issue
        id: extract
        run: |
          TITLE="${{ github.event.issue.title }}"
          BODY=$(echo "${{ github.event.issue.body }}" | tr -d '\r')
          LANG=$(echo "$TITLE" | grep -oP '\(\K[^)]+')
          ENGLISH_WORD=$(echo "$BODY" | grep -oP 'English: \*\*\K[^*]+')
          TARGET_WORD=$(echo "$BODY" | grep -oP 'Target \([^)]+\): \*\*\K[^*]+')
          SAFE_TARGET_WORD=$(echo "$TARGET_WORD" | tr -cd '[:alnum:]_' | cut -c1-20)
          BRANCH="learned-${SAFE_TARGET_WORD:-word}-${RANDOM}"

          echo "Extracted Lang: $LANG"
          echo "Extracted English: $ENGLISH_WORD"
          echo "Extracted Target: $TARGET_WORD"
          echo "Branch Name: $BRANCH"

          if [ -z "$LANG" ] || [ -z "$ENGLISH_WORD" ] || [ -z "$TARGET_WORD" ]; then
            echo "Error: Failed to extract required information from issue title/body."
            exit 1
          fi

          echo "lang=$LANG" >> $GITHUB_OUTPUT
          echo "english_word=$ENGLISH_WORD" >> $GITHUB_OUTPUT
          echo "target_word=$TARGET_WORD" >> $GITHUB_OUTPUT
          echo "branch=$BRANCH" >> $GITHUB_OUTPUT
        shell: bash

      - name: Create and switch to new branch
        run: |
          git checkout -b ${{ steps.extract.outputs.branch }}
        shell: bash

      - name: Update learned words JSON
        run: |
          FILE="data/learned_${{ steps.extract.outputs.lang }}.json"
          ENGLISH_WORD="${{ steps.extract.outputs.english_word }}"
          TARGET_WORD="${{ steps.extract.outputs.target_word }}"

          echo "Updating file: $FILE"
          mkdir -p data
          if [ ! -f "$FILE" ]; then
            echo '{"words":[]}' > "$FILE"
            echo "Created initial file $FILE"
          fi

          # Add the object using jq (same logic as before)
          jq --arg eng "$ENGLISH_WORD" --arg tgt "$TARGET_WORD" \
             'if (.words | map(.target) | index($tgt)) == null then .words += [{"english": $eng, "target": $tgt}] else . end' \
             "$FILE" > tmp.$$.json && mv tmp.$$.json "$FILE"

          echo "JSON file updated."
          git add "$FILE"
          git commit -m "Add learned pair: ${ENGLISH_WORD} / ${TARGET_WORD} (${{ steps.extract.outputs.lang }})"
          git push origin ${{ steps.extract.outputs.branch }}
        shell: bash

      # **** REPLACED create-pull-request ACTION WITH gh CLI ****
      - name: Create Pull Request using GitHub CLI
        env:
          # **** USE THE REPOSITORY SECRET INSTEAD OF THE DEFAULT TOKEN ****
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          echo "Creating PR for branch: ${{ steps.extract.outputs.branch }}"
          gh pr create \
            --base "main" \
            --head "${{ steps.extract.outputs.branch }}" \
            --title "Learned: ${{ steps.extract.outputs.english_word }} / ${{ steps.extract.outputs.target_word }} (${{ steps.extract.outputs.lang }})" \
            --body "Automatically adding learned word pair triggered by issue #${{ github.event.issue.number }}. Please review and merge." \
            --label "learned-word,automated-pr"
        shell: bash